name: generate pacman graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@v3.2.5
        with:
          github_user_name: Y4ELX

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
